#!/usr/bin/perl
#

use strict;
use warnings;
use feature qw(switch);
no warnings 'experimental';

#Where to find our library and auxiliary code.
use FindBin qw($Bin);
use lib $ENV{ATTENSW} || "/projects/usbAtten_controller/perl";

use lib "$Bin/..";
use lib "$Bin";

my $att = shift(@ARGV);

use AttenSwitch;

my $dut    = AttenSwitch->new();
my $result = $dut->connect();
if ( $result == AttenSwitch::SUCCESS ) {
  print("Got device\n");
}

my $attSel;

given ($att) {
  when (0)  { $attSel = AttenSwitch::ATTEN->ATT_0DB; }
  when (10) { $attSel = AttenSwitch::ATTEN->ATT_10DB; }
  when (20) { $attSel = AttenSwitch::ATTEN->ATT_20DB; }
  when (30) { $attSel = AttenSwitch::ATTEN->ATT_30DB; }
  when (40) { $attSel = AttenSwitch::ATTEN->ATT_40DB; }
  when (50) { $attSel = AttenSwitch::ATTEN->ATT_50DB; }
  when (60) { $attSel = AttenSwitch::ATTEN->ATT_60DB; }
  when (70) { $attSel = AttenSwitch::ATTEN->ATT_70DB; }
}
$dut->atten($attSel);
printf("ok\n");
exit;
