#!/usr/bin/perl
#

use strict;
use warnings;

#Where to find our library and auxiliary code.
use FindBin qw($Bin);
use lib $ENV{ATTENSW} || "/projects/usbAtten_controller/perl";

use lib "$Bin/..";
use lib "$Bin";

use AttenSwitch;

my $dut = AttenSwitch->new();
my $result = $dut->connect();
if ($result == AttenSwitch::SUCCESS) {
  print("Got device\n");
}
