#!/usr/bin/perl
#

use strict;
use warnings;

#Where to find our library and auxiliary code.
use FindBin qw($Bin);
use lib $ENV{ATTENSW} || "/projects/usbAtten_controller/perl";

use lib "$Bin/..";
use lib "$Bin";

use AttenSwitch;

my $dut    = AttenSwitch->new(PID=>0x0004);
my $result = $dut->connect();
if ( $result == AttenSwitch::SUCCESS ) {
  print("Got device\n");
}

my $outPkt = AttenSwitch::Packet->new(
  command => AttenSwitch::COMMAND->ECHO,
  payload => "ABCDEF"
);

print("Sending:\n");
$outPkt->dump();

my ( $res, $rpkt ) = $dut->send_packet($outPkt);
printf( "Got result: %s\n", $res == AttenSwitch::SUCCESS ? "SUCCESS" : "FAIL" );
printf("Receive packet:\n");
$rpkt->dump();

