#!/usr/bin/perl
#

use strict;
use warnings;
use feature qw(switch);
no warnings 'experimental';

#Where to find our library and auxiliary code.
use FindBin qw($Bin);
use lib $ENV{ATTENSW} || "/projects/usbAtten_controller/perl";

use lib "$Bin/..";
use lib "$Bin";

my $sw = shift(@ARGV);

use AttenSwitch;

my $dut = AttenSwitch->new();
my $result = $dut->connect();
if ($result == AttenSwitch::SUCCESS) {
  print("Got device\n");
}

my $swSel;

given ($sw) {
  when(1) { $swSel = AttenSwitch::SP8TSETTING->J1; }
  when(2) { $swSel = AttenSwitch::SP8TSETTING->J2; }
  when(3) { $swSel = AttenSwitch::SP8TSETTING->J3; }
  when(4) { $swSel = AttenSwitch::SP8TSETTING->J4; }
  when(5) { $swSel = AttenSwitch::SP8TSETTING->J5; }
  when(6) { $swSel = AttenSwitch::SP8TSETTING->J6; }
  when(7) { $swSel = AttenSwitch::SP8TSETTING->J7; }
  when(8) { $swSel = AttenSwitch::SP8TSETTING->J8; }
  default { $swSel = AttenSwitch::SP8TSETTING->J1; }
}

$dut->sp8t($swSel);
printf("ok\n");
exit;
