#!/usr/bin/perl
#

use strict;
use warnings;

#Where to find our library and auxiliary code.
use FindBin qw($Bin);
use lib $ENV{ATTENSW} || "/projects/usbAtten_controller/perl";

use lib "$Bin/..";
use lib "$Bin";

my $sw      = shift(@ARGV);
my $setting = uc( shift(@ARGV) );

use AttenSwitch;

my $dut = AttenSwitch->new( PID => 0x0004 );
my $result = $dut->connect();
if ( $result == AttenSwitch::SUCCESS ) {
  print("Got device\n");
}

my $swSel;
my $s;

SW: {
  if ( $setting eq "1" || $setting eq "A" ) {
    $s = AttenSwitch::SPDTSETTING->J1SEL;
    last SW;
  }
  if ( $setting eq "2" || $setting eq "B" ) {
    $s = AttenSwitch::SPDTSETTING->J2SEL;
    last SW;
  }
}

if ( $sw eq "1" || $sw eq "3" ) { $dut->spdt( AttenSwitch::SPDTSEL->SW1, $s ); }
if ( $sw eq "2" || $sw eq "3" ) { $dut->spdt( AttenSwitch::SPDTSEL->SW2, $s ); }

printf("ok\n");
exit;
