#!/usr/bin/perl
#

my $name=shift;


my $c_skel=<<'EoF';
/*******************************************************************************
* Copyright (C) __YY__ __UNAME__ (__UMAIL__), All rights reserved.
*
*
* Filename:     __FNAME__
*
* Description: __CHIPU__ The author neglected to write a description.
*
*******************************************************************************/
//#define TRACE_PRINT 1

#include "OSandPlatform.h"

#define GLOBAL___CHIPU__
#include "__HDR__"
EoF

my $h_skel=<<'EoF';
/*******************************************************************************
* Copyright (C) __YY__ __UNAME__ (__UMAIL__), All rights reserved.
*
*
* Filename:     __HDR__
*
* Description: __CHIPU__  The author neglected to write a description.
*
*******************************************************************************/
//#define TRACE_PRINT 1

#ifndef ___CHIPU___INCLUDED
#define ___CHIPU___INCLUDED

#include "OSandPlatform.h"

#ifdef GLOBAL___CHIPU__
#define __CHIPU__GLOBAL
#define __CHIPU__PRESET(A) = (A)
#else
#define __CHIPU__PRESET(A)
#ifdef __cplusplus
#define __CHIPU__GLOBAL extern "C"
#else
#define __CHIPU__GLOBAL extern
#endif	/*__cplusplus*/
#endif				/*GLOBAL___CHIPU__ */

// ----------------------------------------------------------------
// PRIVATE API AND SUBJECT TO CHANGE!
// ----------------------------------------------------------------

// ----------------------------------------------------------------
// PUBLIC API definition
// ----------------------------------------------------------------

#endif				//___CHIPU___INCLUDED
EoF

my $uname = `git config --global user.name`;
chomp($uname); chomp($uname);
my $umail = `git config --global user.email`;
chomp($umail); chomp($umail);
my $yy = sprintf("%4d",(localtime(time))[5] + 1900);

my $hdr="$name". ".h";
my $cfile="$name".".c";

die("$hdr already exists.") if ( -f $hdr );
die("$cfile already exists.") if ( -f $cfile );


my $chipu = uc($name);
$c_skel =~s/__CHIPU__/$chipu/g;
$c_skel =~s/__HDR__/$hdr/g;
$c_skel =~s/__FNAME__/$cfile/g;
$c_skel =~s/__YY__/$yy/g;
$c_skel =~s/__UNAME__/$uname/g;
$c_skel =~s/__UMAIL__/$umail/g;

$h_skel =~s/__CHIPU__/$chipu/g;
$h_skel =~s/__HDR__/$hdr/g;
$h_skel =~s/__YY__/$yy/g;
$h_skel =~s/__UNAME__/$uname/g;
$h_skel =~s/__UMAIL__/$umail/g;


open (CS,">$cfile");
print CS $c_skel;
close CS;

open(HS,">$hdr");
print HS $h_skel;
close(HS);
